[package]
name = "rust_component"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2"
actix-web = "4"
actix-cors = "0.7"
serde = { version = "1.0", features = ["derive"] }
rayon = "1"

[lib]
crate-type = ["cdylib"]
rust_component = { path = "../rust_component" }
